### ISSUE TITLE
Processing parameters

### ISSUE THREAD

**Issue by ttsukianto** [ttsukianto/esip_julia_aws#1]
From the station information returned when a user clicks on "Query" -> "Save Selected", how would I get the filtermin, filtermax, and xcor length parameters?

**Comment by dylanmikesell** [comment]
These should all be provided by the user. They are part of the user input. Did you have a chance to look at the idea of making two tabs? One for the current page that includes the map and station selection. The other for the user inputs for the crosscorrelation parameters. The station selection stuff is looking great by the way!

**Comment by ttsukianto** [comment]
Thanks! I'll try to get the second tab up on Wednesday.

**Comment by dylanmikesell** [comment]
Here is the list of processing parameters that we will need the user to input. The values after the equal sign can be the default values that initially populate the fields.

fs            = 10.0       # resample frequency in Hz
freqmin  = 0.1         #  minimum frequency in Hz
freqmax = 0.2         # maximum frequency in Hz
cc_step  = 450       # correlation step  in sec
cc_len    = 1800      # correlation length in sec
maxlag   = 60.0       # maximum lag time in correlation in sec

We may need to add others later, but these are what we need to start. Here is the complete list of input parameters.

https://github.com/tclements/SeisNoise.jl/blob/master/src/Types/InputParams.jl
