### ISSUE TITLE
JSON or CSV

### ISSUE THREAD

**Issue by dylanmikesell** [ttsukianto/esip_julia_aws#4]
When the user presses Save Selected, we need to write the data to a json or csv file. This is the file that is then read into Julia to decide which stations, which channels, over what time range is downloaded from IRIS and processed.

This is how to write to JSON: https://stackoverflow.com/questions/36856232/write-add-data-in-json-file-using-node-js

Here is a CSV example: https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side

We need to write the following information to the file for each station.

Network, Station, Location, Channel, Start time, Stop time

**Comment by ttsukianto** [comment]
- Is there a preference for start time/stop time format? The map tab currently outputs it as a string such as "2004-09-19T00:00:00".
- ~~I don't know if I'm missing something, but I'm looking at the example IRIS queries and it doesn't look like the location code is returned in the XML file. Should we require the user to input the location code?~~ Figured it out. Had to change the granularity of the request

**Comment by dylanmikesell** [comment]
That time format is fine. That is actually exactly what we need.
